#ifndef COMPLEX_H_INCLUDED
#define COMPLEX_H_INCLUDED

void ke_complex_print(sml_t* sml, ke1_t *k);
void ke_complex_hash(sml_t* sml);

#define COMPLEX "complex"
#define COMPLEX_SET_REAL "complex_set_real"
#define COMPLEX_SET_IMAG "complex_set_imag"
#define COMPLEX_ARG "complex_arg"
#define COMPLEX_ABS "complex_abs"
#define COMPLEX_ABS2 "complex_abs2"
#define COMPLEX_LOGABS "complex_logabs"
#define COMPLEX_ADD "complex_add"
#define COMPLEX_SUB "complex_sub"
#define COMPLEX_MUL "complex_mul"
#define COMPLEX_DIV "complex_div"
#define COMPLEX_ADD_REAL "complex_add_real"
#define COMPLEX_SUB_REAL "complex_sub_real"
#define COMPLEX_MUL_REAL "complex_mul_real"
#define COMPLEX_DIV_REAL "complex_div_real"
#define COMPLEX_ADD_IMAG "complex_add_imag"
#define COMPLEX_SUB_IMAG "complex_sub_imag"
#define COMPLEX_MUL_IMAG "complex_mul_imag"
#define COMPLEX_DIV_IMAG "complex_div_imag"
#define COMPLEX_CONJUGATE "complex_congugate"
#define COMPLEX_INVERSE "complex_inverse"
#define COMPLEX_NEGATIVE "complex_negative"

#define COMPLEX_SQRT "complex_sqrt"
#define COMPLEX_SQRT_REAL "complex_sqrt_real"
#define COMPLEX_POW "complex_pow"
#define COMPLEX_POW_REAL "complex_pow_real"
#define COMPLEX_EXP "complex_exp"
#define COMPLEX_LOG "complex_log"
#define COMPLEX_LOG10 "complex_log10"
#define COMPLEX_LOG_B "complex_log_b"
#define COMPLEX_SIN "complex_sin"
#define COMPLEX_COS "complex_cos"
#define COMPLEX_TAN "complex_tan"
#define COMPLEX_SEC "complex_sec"
#define COMPLEX_CSC "complex_csc"
#define COMPLEX_COT "complex_cot"
#define COMPLEX_ARCSIN "complex_arcsin"
#define COMPLEX_ARCSIN_REAL "complex_arcsin_real"
#define COMPLEX_ARCCOS "complex_arccos"
#define COMPLEX_ARCCOS_REAL "complex_arccos_real"
#define COMPLEX_ARCTAN "complex_arctan"
#define COMPLEX_ARCSEC "complex_arcsec"
#define COMPLEX_ARCSEC_REAL "complex_arcsec_real"
#define COMPLEX_ARCCSC "complex_arccsc"
#define COMPLEX_ARCCSC_REAL "complex_arccsc_real"
#define COMPLEX_ARCCOT "complex_arccot"
#define COMPLEX_SINH "complex_sinh"
#define COMPLEX_COSH "complex_cosh"
#define COMPLEX_TANH "complex_tanh"
#define COMPLEX_SECH "complex_sech"
#define COMPLEX_CSCH "complex_csch"
#define COMPLEX_COTH "complex_coth"
#define COMPLEX_ARCSINH "complex_arcsinh"
#define COMPLEX_ARCCOSH "complex_arccosh"
#define COMPLEX_ARCTANH "complex_arctanh"
#define COMPLEX_ARCSECH "complex_arcsech"
#define COMPLEX_ARCCSCH "complex_arccsch"
#define COMPLEX_ARCCOTH "complex_arccoth"


#endif // COMPLEX_H_INCLUDED
