#ifndef FILE_H_INCLUDED
#define FILE_H_INCLUDED

#define FILE_FCLOSE "fclose"
#define FILE_CLEARERR "clearerr"
#define FILE_FEOF "feof"
#define FILE_FERROR "ferror"
#define FILE_FFLUSH "fflush"
#define FILE_FGETPOS "fgetpos"
#define FILE_FOPEN "fopen"
#define FILE_FREAD "fread"
#define FILE_FREOPEN "freopen"
#define FILE_FSEEK "fseek"
#define FILE_FSETPOS "fsetpos"
#define FILE_FTELL "ftell"
#define FILE_FWRITE "fwrite"
#define FILE_REMOVE "remove"
#define FILE_RENAME "rename"
#define FILE_REWIND "rewind"
#define FILE_SETBUF "setbuf"
#define FILE_SETVBUF "setvbuf"
#define FILE_TMPFILE "tmpfile"
#define FILE_SETNAME "setnam"
#define FILE_FPRINTF "fprintf"
#define FILE_FPRINT "fprint"
#define FILE_SPRINTF "sprintf"
#define FILE_VFPRINTF "vfprintf"
#define FILE_VPRINTF "vprintf"
#define FILE_VSPRINTF "vsprintf"
#define FILE_FSCANF "fscanf"
#define FILE_SCANF "scanf"
#define FILE_SSCANF "sscanf"
#define FILE_FGETC "fgetc"
#define FILE_FGETS "fgets"
#define FILE_FPUTC "fputc"
#define FILE_FPUTS "fputs"
#define FILE_GETC "getc"
#define FILE_GETCHAR "getchar"
#define FILE_GETS "gets"
#define FILE_PUTC "putc"
#define FILE_PUTCHAR "putchar"
#define FILE_PUTS "puts"
#define FILE_UNGETC "ungetc"
#define FILE_PERROR "perror"


#endif // FILE_H_INCLUDED

