#ifndef PLOT_H_INCLUDED
#define PLOT_H_INCLUDED

void ke_plot_hash();

#define PLOT "plot"
#define PLOT_INIT "plot_init"
#define PLOT_PLPAUSE "plot_pause"
#define PLOT_PLSPAUSE "plot_spause"
#define PLOT_PLENV "plot_env"
#define PLOT_PLDEV "plot_dev"
#define PLOT_PLSDEV "plot_sdev"
#define PLOT_PLLINE "plot_line"
#define PLOT_PLEND "plot_end"
#define PLOT_PLSETCONTLABELFORMAT "plot_setcontentlableformat"
#define PLOT_PLSETCONTLABELPARAM "plot_setcontentlabelparam"
#define PLOT_PLADV "plot_adv"
#define PLOT_PLARC "plot_arc"
#define PLOT_PLAXES "plot_axes"
#define PLOT_PLBIN "plot_bin"
#define PLOT_PLBOP "plot_bop"
#define PLOT_PLBOX "plot_box"
#define PLOT_PLBOX3 "plot_box3"
#define PLOT_PLBTIME "plot_btime"
#define PLOT_PLCTIME "plot_ctime"
#define PLOT_PLCALCWORLD "plot_calc_world"
#define PLOT_PLCLEAR "plot_clear"
#define PLOT_PLCOL0 "plot_col0"
#define PLOT_PLCOL1 "plot_col1"
#define PLOT_PLCOLORBAR "plot_colorbar"
#define PLOT_PLCONFIGTIME "plot_configtime"
#define PLOT_PLCONT "plot_cont"
#define PLOT_PLCPSTRM "plot_cpstrm"
#define PLOT_PLEND1 "plot_end1"
#define PLOT_PLENV0 "plot_env0"
#define PLOT_PLEOP "plot_eop"
#define PLOT_PLERRX "plot_errx"
#define PLOT_PLERRY "plot_erry"
#define PLOT_PLFAMADV "plot_famadv"
#define PLOT_PLFILL "plot_fill"
#define PLOT_PLFILL3 "plot_fill3"
#define PLOT_PLFLUSH "plot_flush"
#define PLOT_PLFONT "plot_font"
#define PLOT_PLFONTLD "plot_fontld"
#define PLOT_PLGETCURSOR "plot_GetCursor"
#define PLOT_PLGCHR "plot_gchr"
#define PLOT_PLGCMAP1RANGE "plot_gcmap1_range"
#define PLOT_PLGCOL0 "plot_gcol0"
#define PLOT_PLGCOL0A "plot_gcol0a"
#define PLOT_PLGCOLBG "plot_gcolbg"
#define PLOT_PLGCOLBGA "plot_gcolbga"

#endif // COMPLEX_H_INCLUDED
