#ifndef VECTOR_H_INCLUDED
#define VECTOR_H_INCLUDED

void ke_vector_print(ke1_t *k);
void ke_vector_hash();
void ke_vector_freemem(ke1_t *e);

#define VECTOR "vector"
#define VECTOR_ALLOC "vector_alloc"
#define VECTOR_GET "vector_get"
#define VECTOR_SET "vector_set"
#define VECTOR_PUT "vector_put"
#define VECTOR_FREE "vector_free"
#define VECTOR_SET_ALL "vector_set_all"
#define VECTOR_SET_ZERO "vector_set_zero"
#define VECTOR_SET_BASIS "vector_set_basis"
#define VECTOR_ADD "vector_add"
#define VECTOR_SUB "vector_sub"
#define VECTOR_MUL "vector_mul"
#define VECTOR_DIV "vector_div"
#define VECTOR_SCALE "vector_scale"
#define VECTOR_ADD_CONSTANT "vector_add_constant"
#define VECTOR_REVERSE "vector_reverse"
#define VECTOR_SWAP_ELEMENTS "vector_swap_elements"
#define VECTOR_MEMCPY "vector_memcpy"
#define VECTOR_SWAP "vector_swap"
#define VECTOR_MIN "vector_min"
#define VECTOR_MAX "vector_max"
#define VECTOR_ISNULL "vector_isnull"
#define VECTOR_ISPOS "vector_ispos"
#define VECTOR_ISNEG "vector_isneg"
#define VECTOR_ISNONNEG "vector_isnonneg"
#define VECTOR_EQUAL "vector_equal"
#define VECTOR_FSCANF "vector_fscanf"
#define VECTOR_SCAN "vector_scan"
#define VECTOR_FPRINTF "vector_fprintf"
#define VECTOR_PRINT "vector_print"
#define VECTOR_FREAD "vector_fread"
#define VECTOR_READ "vector_read"
#define VECTOR_FWRITE "vector_fwrite"
#define VECTOR_WRITE "vector_write"


#define VECTOR_INT_ALLOC "vector_int_alloc"
#define VECTOR_INT_GET "vector_int_get"
#define VECTOR_INT_SET "vector_int_set"
#define VECTOR_INT_PUT "vector_int_put"
#define VECTOR_INT_FREE "vector_int_free"
#define VECTOR_INT_SET_ALL "vector_int_set_all"
#define VECTOR_INT_SET_ZERO "vector_int_set_zero"
#define VECTOR_INT_SET_BASIS "vector_int_set_basis"
#define VECTOR_INT_ADD "vector_int_add"
#define VECTOR_INT_SUB "vector_int_sub"
#define VECTOR_INT_MUL "vector_int_mul"
#define VECTOR_INT_DIV "vector_int_div"
#define VECTOR_INT_SCALE "vector_int_scale"
#define VECTOR_INT_ADD_CONSTANT "vector_int_add_constant"
#define VECTOR_INT_REVERSE "vector_int_reverse"
#define VECTOR_INT_SWAP_ELEMENTS "vector_int_swap_elements"
#define VECTOR_INT_MEMCPY "vector_int_memcpy"
#define VECTOR_INT_SWAP "vector_int_swap"
#define VECTOR_INT_MIN "vector_int_min"
#define VECTOR_INT_MAX "vector_int_max"
#define VECTOR_INT_ISNULL "vector_int_isnull"
#define VECTOR_INT_ISPOS "vector_int_ispos"
#define VECTOR_INT_ISNEG "vector_int_isneg"
#define VECTOR_INT_ISNONNEG "vector_int_isnonneg"
#define VECTOR_INT_EQUAL "vector_int_equal"
#define VECTOR_INT_FSCANF "vector_int_fscanf"
#define VECTOR_INT_SCAN "vector_int_scan"
#define VECTOR_INT_FPRINTF "vector_int_fprintf"
#define VECTOR_INT_PRINT "vector_int_print"
#define VECTOR_INT_FREAD "vector_int_fread"
#define VECTOR_INT_READ "vector_int_read"
#define VECTOR_INT_FWRITE "vector_int_fwrite"
#define VECTOR_INT_WRITE "vector_int_write"

#endif // VECTOR_H_INCLUDED
